pipeline {
    agent any
    tools {
        maven 'MAVEN'
    }
    environment {
        NEXUS_URL = 'http://nexus:8081'
        NEXUS_REPOSITORY = 'maven-snapshots'
        ARTIFACT_GROUP = 'com.example.laundry'
        ARTIFACT_ID = 'LaundryApp'
        ARTIFACT_VERSION = '1.0-SNAPSHOT'
        ARTIFACT_FILE = 'maven-app/target/LaundryApp-1.0-SNAPSHOT.jar'
        NEXUS_CREDENTIALS = 'nexus'
    }

    stages {
        stage('stage1 Clone Code') {
            steps {
                git branch: 'main', credentialsId: 'GIT-TOKEN-READONLY', url: 'https://github.com/devopsdecode/april-2025.git'
            }
        }

        stage('BUILD and Package') {
            steps {
                dir('maven-app') {
                    sh 'mvn package'
                }
            }
        }

        stage('Push to nexus') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: NEXUS_CREDENTIALS, usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                        dir('maven-app') { // Corrected: This dir block needs to be active
                            sh """
                            mvn deploy:deploy-file \
                                -Durl=${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/ \
                                -DrepositoryId=nexus \
                                -Dfile=target/LaundryApp-1.0-SNAPSHOT.jar \
                                -DgroupId=${ARTIFACT_GROUP} \
                                -DartifactId=${ARTIFACT_ID} \
                                -Dversion=${ARTIFACT_VERSION} \
                                -Dpackaging=jar \
                                --settings ./setting.xml
                            """
                        }
                    }
                }
            }
        }
    }
}